openapi: 3.0.3
info:
  title: Event Validation API
  version: 0.1.0
  description: |
    API for validating webhook events, retrieving schema metadata, and publishing to MSK ingress topics.
servers:
  - url: https://api.mycorp.example
    description: Production
  - url: https://api.sandbox.mycorp.example
    description: Sandbox
paths:
  /events/{eventName}:
    post:
      summary: Validate and enqueue an event payload
      description: >-
        Validates an inbound payload against the configured schema and, if successful,
        publishes it to the matching MSK ingress topic.
      operationId: publishEvent
      parameters:
        - name: eventName
          in: path
          required: true
          schema:
            type: string
          description: Logical event name (e.g., CustomerUpdated)
        - name: producer-domain
          in: header
          required: true
          schema:
            type: string
          description: Producer domain used for routing and topic derivation
        - name: schema-id
          in: header
          required: true
          schema:
            type: string
          description: Identifier of the schema stored in DynamoDB
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventPayload'
      responses:
        '202':
          description: Payload accepted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckResponse'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Duplicate or conflicting idempotency key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Downstream Kafka unavailable or throttled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /events/all:
    get:
      summary: List all active schemas
      description: >-
        Retrieves all active schema definitions from the event_schema table.
        Returns a list of schema metadata including domain, event name, version, and schema definitions.
      operationId: getAllSchemas
      responses:
        '200':
          description: List of all active schemas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchemaMetadata'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /events/schema_id/{schemaId}:
    get:
      summary: Retrieve schema by EVENT_SCHEMA_ID
      description: >-
        Retrieves a complete schema definition from the event_schema DynamoDB table
        by matching the EVENT_SCHEMA_ID attribute. Returns all schema metadata including
        domain, event name, version, schema definitions (JSON, XML, Avro), sample events,
        and administrative metadata.
      operationId: getSchemaBySchemaId
      parameters:
        - name: schemaId
          in: path
          required: true
          schema:
            type: string
          description: The EVENT_SCHEMA_ID value to search for (e.g., SCHEMA_0001, SCHEMA_TRANSACTION_CREATED_V1)
          example: SCHEMA_0001
      responses:
        '200':
          description: Schema found and returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaDetailResponse'
        '404':
          description: Schema not found for the given schemaId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Publish event by schema ID with Avro conversion
      description: >-
        Validates an inbound payload against the schema identified by EVENT_SCHEMA_ID,
        converts it to Avro binary format, and publishes it to the configured Kafka topic.
        The payload can be in JSON, XML, or Avro format (specified via Content-Type header).
        All formats are validated and converted to Avro binary before publishing.
      operationId: publishEventBySchemaId
      parameters:
        - name: schemaId
          in: path
          required: true
          schema:
            type: string
          description: The EVENT_SCHEMA_ID value to identify the schema
          example: SCHEMA_0001
        - name: Content-Type
          in: header
          required: false
          schema:
            type: string
            enum: [application/json, application/xml, application/avro]
          description: Format of the incoming payload (defaults to application/json)
        - name: X-Event-Id
          in: header
          required: false
          schema:
            type: string
            format: uuid
          description: Optional event ID (generated if not provided)
        - name: Idempotency-Key
          in: header
          required: false
          schema:
            type: string
          description: Optional idempotency key for duplicate detection
      requestBody:
        required: true
        description: Event payload in JSON, XML, or Avro format
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
          application/xml:
            schema:
              type: string
          application/avro:
            schema:
              type: object
              additionalProperties: true
      responses:
        '202':
          description: Event accepted and published to Kafka in Avro format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckResponse'
        '400':
          description: Validation failed, schema/topic inactive, or Avro schema missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Schema not found for the given schemaId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Kafka unavailable or publish failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /schemas/{domain}/{event}/{version}:
    get:
      summary: Retrieve schema metadata for a specific event version
      operationId: fetchSchema
      parameters:
        - name: domain
          in: path
          required: true
          schema:
            type: string
        - name: event
          in: path
          required: true
          schema:
            type: string
        - name: version
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Schema metadata located
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaMetadata'
        '404':
          description: Schema not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    EventPayload:
      type: object
      required:
        - eventId
        - occurredAt
        - data
      properties:
        eventId:
          type: string
          format: uuid
        occurredAt:
          type: string
          format: date-time
        correlationId:
          type: string
        schemaVersion:
          type: string
        data:
          type: object
          additionalProperties: true
    AckResponse:
      type: object
      required:
        - status
        - eventId
      properties:
        status:
          type: string
          example: ACCEPTED
        eventId:
          type: string
          format: uuid
        enqueueTimestamp:
          type: string
          format: date-time
    SchemaMetadata:
      type: object
      required:
        - schemaId
        - format
        - transformFlag
      properties:
        schemaId:
          type: string
        format:
          type: string
          enum: [JSON, XML, SOAP, AVRO]
        transformFlag:
          type: string
          enum: [Y, N]
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
        eventName:
          type: string
        producerDomain:
          type: string
        schemaDefinition:
          type: string
          description: Underlying JSON Schema, XSD, or Avro definition
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          example: VALIDATION_FAILED
        message:
          type: string
        details:
          type: array
          items:
            type: string
    SchemaDetailResponse:
      type: object
      description: Complete schema metadata from DynamoDB including all attributes
      properties:
        eventSchemaId:
          type: string
          description: The EVENT_SCHEMA_ID identifier
          example: SCHEMA_0001
        producerDomain:
          type: string
          description: Producer domain name
          example: payments
        eventName:
          type: string
          description: Event name
          example: transactionCreated
        version:
          type: string
          description: Schema version
          example: "1.0"
        eventSchemaHeader:
          type: string
          description: Description of the event schema header
        eventSchemaDefinitionJson:
          type: string
          description: JSON Schema definition
        eventSchemaDefinitionXml:
          type: string
          description: XML Schema (XSD) definition
        eventSchemaDefinitionAvro:
          type: string
          description: Avro Schema definition
        eventSample:
          type: string
          description: Sample event payload in JSON format
        eventSchemaStatus:
          type: string
          enum: [ACTIVE, INACTIVE]
          description: Status of the schema
        hasSensitiveData:
          type: string
          enum: [YES, NO]
          description: Indicates if the event contains sensitive data
        producerSystemUsersId:
          type: string
          description: User ID who created the schema
        topicName:
          type: string
          description: Kafka topic name
          example: payments.transaction.created
        topicStatus:
          type: string
          enum: [ACTIVE, INACTIVE]
          description: Status of the Kafka topic
        insertTs:
          type: string
          format: date-time
          description: Timestamp when the schema was inserted
          nullable: true
        insertUser:
          type: string
          description: User who inserted the schema
        updateTs:
          type: string
          format: date-time
          description: Timestamp when the schema was last updated
          nullable: true
        updateUser:
          type: string
          description: User who last updated the schema
